### ISSUE TITLE
Does this repository not finished?

### ISSUE THREAD

**Issue by chinesedfan** [vicky002/1000_Projects#8]
I just find problems names with simple descriptions. No more detail information and no solutions in [vicky002/Project_Solutions](https://github.com/vicky002/Project_Solutions).

Do I miss something?

**Comment by in-just** [comment]
I noticed this as well. There doesn't appear to be any solved projects whatsoever.

**Comment by JakeNocentino** [comment]
I think that's the point; this is simply a list of projects you could make. Including the solutions would make this idea obsolete.

**Comment by in-just** [comment]
No, not if there's literally a link for "Project Solutions." 

I'm starting to think this project is just a cash grab for donations, it's the first large picture you see for it.

**Comment by chinesedfan** [comment]
Hi @vicky002, can you share some words to explain before closing?

**Comment by vicky002** [comment]
Hi @chinesedfan , Sorry but I longer have time to maintain this repository and work on solutions. This repository only provides the list of all possible projects that can be done. We never promised to provide all the solutions to all the projects. I wanted the community to work on the project solutions and give links to it but it didn't happen.

If you have time, I'd love to make some maintainer of this repository and let him/her work on the solutions.

**Comment by chinesedfan** [comment]
@vicky002 I also have not much time to implement solutions for those projects. But glad to maintain this repository. At least, I can help you reply issues to avoid confusions like me and @in-just. 😆
